checks:
  php: true

filter:
  excluded_paths:
    - tests/*

build:
  nodes:
    analysis:
      tests:
        override:
          - command: phpcs-run --config phpcs.xml
    php72:
      environment:
        php:
          version: 7.2
      tests:
        override:
          - php-scrutinizer-run
          - command: vendor/bin/phpunit --coverage-clover=coverage72 --prepend .coverage-filter.php
            coverage:
              file: coverage72
              format: php-clover
    php73:
      environment:
        php:
          version: 7.3
      tests:
        override:
          - php-scrutinizer-run
          - command: vendor/bin/phpunit --coverage-clover=coverage73 --prepend .coverage-filter.php
            coverage:
              file: coverage73
              format: php-clover
    php74:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run
          - command: vendor/bin/phpunit --coverage-clover=coverage74 --prepend .coverage-filter.php
            coverage:
              file: coverage74
              format: php-clover