checks:
  php: true

filter:
  excluded_paths:
    - tests/*

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: false
    php72:
      environment:
        php:
          version: 7.2
      tests:
        override:
          - command: phpunit --prepend .coverage-filter.php
    php73:
      environment:
        php:
          version: 7.3
      tests:
        override:
          - command: phpunit --prepend .coverage-filter.php
    php74:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - command: phpunit --coverage-clover=my-coverage-file --prepend .coverage-filter.php
            coverage:
              file: my-coverage-file
              format: php-clover